---
- name: install utility softwares
  become: yes
  hosts: application
  vars:
    utilities:
      - git
      - nano
      - tree
  tasks:
    - name: install utilites
      ansible.builtin.apt:
        name: "{{ utilities }}"
        update_cache: yes
        state: present
